version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 16...
      - yum install https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - yum install --no-install-recommends 
    build:
    commands:
      - echo Installing dependencies...
      - yum
  build:
    commands:
      - echo Testing...
      - yum test
      - echo Building...
      - yum build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
